### ISSUE TITLE
windows11 run failed

### ISSUE THREAD

**Issue by huxulm** [goplus/c2go#226]
It seems cant pass include params to clang?
```
PS H:\Development\github\goplus\c2go\testdata\printf> c2go -v .\printf.c
2024/01/30 11:46:09 ==> runCmd: clang [-E -o H:\Development\github\goplus\c2go\testdata\printf\printf.c.i H:\Development\github\goplus\c2go\testdata\printf\printf.c]
H:\Development\github\goplus\c2go\testdata\printf\printf.c:1:10: fatal error: 'stdio.h' file not found
    1 | #include <stdio.h>
      |          ^~~~~~~~~
1 error generated.
2024/01/30 11:46:09 exit status 1
panic: exit status 1


goroutine 1 [running]:
log.Panicln({0xc000115df8?, 0xc00000a110?, 0xc00000ac10?})
        C:/Program Files/Go/src/log/log.go:446 +0x5a
github.com/goplus/c2go.fatal(...)
        H:/Development/github/goplus/c2go/c2go.go:337
github.com/goplus/c2go.check(...)
        H:/Development/github/goplus/c2go/c2go.go:322
github.com/goplus/c2go.Run({0xa781b8, 0x4}, {0xc00000a110, 0xa}, 0x1, 0xa8b730?)
        H:/Development/github/goplus/c2go/c2go.go:74 +0x134
github.com/goplus/c2go/cmd/c2go/impl.Main(0xc000122000, {0xc0000360d0, 0x2, 0x3})
        H:/Development/github/goplus/c2go/cmd/c2go/impl/c2go.go:76 +0x3d0
main.main()
        H:/Development/github/goplus/c2go/cmd/c2go/main.go:16 +0x77
```

**Comment by xushiwei** [comment]
It only supports linux (ubuntu) and macOS for now.
