### ISSUE TITLE
panic: unexpected: untyped type

### ISSUE THREAD

**Issue by bambuo** [goplus/c2go#6]
# Environment

```
chenchong@family:~/Desktop$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN="/home/chenchong/.local/bin"
GOCACHE="/home/chenchong/.cache/go-build"
GOENV="/home/chenchong/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/chenchong/.local/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/chenchong/.local"
GOPRIVATE=""
GOPROXY="https://proxy.golang.com.cn,direct"
GOROOT="/opt/golang/default"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/opt/golang/default/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1409393763=/tmp/go-build -gno-record-gcc-switches"
```

```
chenchong@family:~/Desktop$ clang -v
Deepin clang version 11.0.1-2
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/8
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

# Code

```c
#include <stdio.h>

int main(){
    char message[] = "Hello,World";
    printf("%s\n",message);
    return 0;
}
```
# Command

```
$ c2go hello.c
```

# Output

```
chenchong@family:~/Desktop$ c2go hello.c
panic: unexpected: untyped type

goroutine 1 [running]:
github.com/goplus/gox.toBasicType(0x40c9e5?, 0x203000?)
        /home/chenchong/.local/pkg/mod/github.com/goplus/gox@v1.10.3/ast.go:180 +0xf7
github.com/goplus/gox.toType(0xc0003e81e0?, {0x7691d8?, 0x8ecb80?})
        /home/chenchong/.local/pkg/mod/github.com/goplus/gox@v1.10.3/ast.go:140 +0x487
github.com/goplus/gox.(*Package).doNewType(0xc0001ec800, 0xc0003e81e0, 0x0, {0xc0003861e0, 0xa}, {0x7691d8, 0x8ecb80}, 0x1)
        /home/chenchong/.local/pkg/mod/github.com/goplus/gox@v1.10.3/type_var_and_const.go:126 +0x457
github.com/goplus/gox.(*CodeBuilder).AliasType(0x7691d8?, {0xc0003861e0?, 0x7692f0?}, {0x7691d8?, 0x8ecb80?}, {0xc000349c80?, 0x0?, 0xa50362aeb70527f4?})
        /home/chenchong/.local/pkg/mod/github.com/goplus/gox@v1.10.3/codebuild.go:582 +0x166
github.com/goplus/c2go/cl.compileTypedef(0xc001a06d00, 0xc0003851e0)
        /home/chenchong/Developer/Codes/gitee/c2go-goplus/cl/type_and_var.go:166 +0x407
github.com/goplus/c2go/cl.compileDeclStmt(0xc001a06d00, 0xc00018a160, 0x1)
        /home/chenchong/Developer/Codes/gitee/c2go-goplus/cl/compile.go:136 +0x310
github.com/goplus/c2go/cl.loadFile(0xc0001ec800, 0xc000349ea8, 0xc00018a160)
        /home/chenchong/Developer/Codes/gitee/c2go-goplus/cl/compile.go:117 +0x17b
github.com/goplus/c2go/cl.NewPackage({0x0, 0x0}, {0x7016e3, 0x4}, 0x0?, 0xc000349ea8)
        /home/chenchong/Developer/Codes/gitee/c2go-goplus/cl/compile.go:75 +0xe5
main.execFile({0x7016e3, 0x4}, {0xc000022803, 0x9}, 0x1, 0x0)
        /home/chenchong/Developer/Codes/gitee/c2go-goplus/cmd/c2go/c2go.go:152 +0xca
main.main()
        /home/chenchong/Developer/Codes/gitee/c2go-goplus/cmd/c2go/c2go.go:82 +0x205
```

**Comment by xushiwei** [comment]
Can you run:

```
c2go -v hello.c
```

and give related error message here?

**Comment by xushiwei** [comment]
linux and windows are not tested now.

**Comment by bambuo** [comment]
> Can you run:
> 
> ```
> c2go -v hello.c
> ```
> 
> and give related error message here?

Because the message is too long, I updated this question and put it at the end

**Comment by bambuo** [comment]
> linux and windows are not tested now.

Is it not supported?

**Comment by xushiwei** [comment]
> > linux and windows are not tested now.
> 
> Is it not supported?

I think need some small fix, but easily to support.

**Comment by xushiwei** [comment]
I know what the problem now.

There is

```c
typedef _IO_lock_t = void
```

in c standard library.

But for now, alias a void type is not allowed.

**Comment by xushiwei** [comment]
I will fix this problem at next release.
